import os

if not os.path.exists("julia_scripts"):
    os.makedirs("julia_scripts")
my_dir = os.path.expanduser("/julia_scripts/test_script.jl")
file = open(my_dir, "w")
file.write("using SubClonalSelection\n")
file.write("l = fitABCmodels(\"oneclone.txt\",\n")
file.write("  \"liver_test\",\n")
file.write("  read_depth = 300,\n")
file.write("  Nmaxinf = 10^2,\n")
file.write("  maxiterations = 5*10^2,\n")
file.write("  resultsdirectory = \"results_test\",\n")
file.write("  save = true,\n")
file.write("  verbose = true,\n")
file.write("  nparticles = 400);\n")
file.write("l\n")
file.write("plotmodelposterior(l)\n")
file.write("plothistogram(l, 0)\n")
file.write("plothistogram(l, 1)\n")
file.write("plothistogram(l, 2)\n")
file.write("plotparameterposterior(l, 0)\n")
file.write("plotparameterposterior(l, 1)\n")
file.write("plotparameterposterior(l, 2)\n")
file.write("saveresults(l, resultsdirectory = \"results_test\")\n")
file.write("saveallplots(l, resultsdirectory = \"results_test\")\n")
file.close()

